### ISSUE TITLE
date file for 

### ISSUE THREAD

**Issue by dnltsk** [kartoza/docker-mapserver#2]
layer is configured with
`DATA "HDF5:/map/MER_FSG_1PNEPA20030129_074733_000001012013_00221_04784_8508_Vaal_chlora.h5://bands/redBand"`

That data needs to be part of the repository. Alternatively we could setup a new different data source.

Thanks and Cheers.

**Comment by NyakudyaA** [comment]
We will replace the data source.  You can also substitute the dataset and use your custom one

**Comment by NyakudyaA** [comment]
closed via  4141c48
